paths:
  data_dir: "./data/"
  output_dir: "./outputs/"
  model_ckpt: "./runs/unet/best.pth"

training:
  epochs: 50
  batch_size: 8
  lr: 1e-4

clustering:
  n_clusters: 4
  m: 2.0
  lambda_bias: 0.5
  max_iter: 100
